version: "3"
services:

  db:
    image: mysql
    container_name: db
    volumes:
      - ./database:/docker-entrypoint-initdb.d:z
      - ./database/db:/var/lib/mysql:z
      - ./database/db:/tmp/:z
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "expenses_schema"
      MYSQL_ROOT_PASSWORD: "password"

  api:
    build: .
    depends_on:
       - "db"
    container_name: expenses_api
    command: npm start
    ports:
      - "3000:3000"